param([string]$ProjectId="liber-apps-cca20",[string]$Region="us-central1")
$ErrorActionPreference="Stop"; Set-StrictMode -Version 3.0
$SourceCandidate="32c2ffd5994d385fb6e7c45414b0b5a0c1188ef5"; $Repo="https://github.com/nvberegovykh/LIBER-Creative.git"; $Work=Join-Path $env:TEMP ("REVEX-RENDER-"+[guid]::NewGuid().ToString("N")); $Source=Join-Path $Work "source"; $ExitCode=1
function Req([string]$n){$c=Get-Command $n -ErrorAction SilentlyContinue|Select-Object -First 1;if(-not $c){throw "$n is required."};$c.Source}
function Run([string]$c,[string[]]$a,[switch]$q){$p=$ErrorActionPreference;try{$ErrorActionPreference="Continue";if($q){& $c @a *> $null}else{& $c @a 2>&1|ForEach-Object{Write-Host ([string]$_)}};$x=$LASTEXITCODE;if($null-eq$x){$x=0};[int]$x}finally{$ErrorActionPreference=$p}}
function Cap([string]$c,[string[]]$a){$p=$ErrorActionPreference;try{$ErrorActionPreference="Continue";$l=@(& $c @a 2>$null|ForEach-Object{[string]$_});$x=$LASTEXITCODE;if($null-eq$x){$x=0};[pscustomobject]@{Code=[int]$x;Text=($l-join"`n").Trim()}}finally{$ErrorActionPreference=$p}}
try{
 Write-Host "REVEX Render-only recovery" -ForegroundColor Cyan; Write-Host "Source: $SourceCandidate"; Write-Host "Scope: Render worker + Render broker only. Energy/Revit/BIM/UI/Docs untouched." -ForegroundColor Green
 $Git=Req "git"; $GCloud=Req "gcloud"; $null=Req "npm"; $null=Req "node"
 $auth=Cap $GCloud @("auth","list","--filter=status:ACTIVE","--format=value(account)"); if($auth.Code-ne0-or-not$auth.Text){Write-Host "Google Cloud sign-in required once..." -ForegroundColor Yellow;if((Run $GCloud @("auth","login"))-ne0){throw "Google Cloud authentication failed."};$auth=Cap $GCloud @("auth","list","--filter=status:ACTIVE","--format=value(account)");if($auth.Code-ne0-or-not$auth.Text){throw "Google Cloud authentication did not complete."}}
 New-Item -ItemType Directory -Path $Work -Force|Out-Null
 if((Run $Git @("init",$Source) -q)-ne0){throw "git init failed."}; if((Run $Git @("-C",$Source,"remote","add","origin",$Repo) -q)-ne0){throw "git remote failed."}; if((Run $Git @("-C",$Source,"fetch","--depth","1","origin",$SourceCandidate))-ne0){throw "Exact Render source fetch failed."}; if((Run $Git @("-C",$Source,"checkout","--detach","FETCH_HEAD") -q)-ne0){throw "Exact Render checkout failed."}; $checked=Cap $Git @("-C",$Source,"rev-parse","HEAD"); if($checked.Text.ToLowerInvariant()-ne$SourceCandidate){throw "Exact-source checkout mismatch."}
 $deploy=Join-Path $Source "server\revex-render-worker\DEPLOY_RENDER_R119.ps1"; if(-not(Test-Path -LiteralPath $deploy -PathType Leaf)){throw "r119 Render deployer missing."}; $code=Run "powershell.exe" @("-NoProfile","-ExecutionPolicy","Bypass","-File",$deploy,"-ProjectId",$ProjectId,"-Region",$Region,"-NoPause"); if($code-ne0){throw "r119 Render deployment failed with exit code $code."}
 Write-Host "PASS: Render worker + broker deployed with persistent Qwen cache." -ForegroundColor Green; Start-Process "https://liberpict.com/liber-apps/apps/revex/index.html?view=bim"; $ExitCode=0
}catch{Write-Host "REVEX Render recovery stopped safely: $($_.Exception.Message)" -ForegroundColor Red;$ExitCode=1}finally{if(Test-Path $Work){try{Remove-Item $Work -Recurse -Force}catch{}};Write-Host "Press Enter to close.";[void](Read-Host)}
exit $ExitCode
