'use strict';
const crypto=require('node:crypto');
const LEASE_MS=12*60*1000;
function createReportJobs({db,now=()=>Date.now(),build}){
 async function claim(projectId,day,revision,signature,force=false){const ref=db.doc(`projects/${projectId}/revexReportJobs/day_${day}`),runId=crypto.randomUUID(),at=now();return db.runTransaction(async tx=>{const s=await tx.get(ref),job=s.exists?s.data():{};if(job.status==='RUNNING'&&Number(job.leaseUntil)>at)return {owned:false,status:'RUNNING',runId:job.runId,day,ref};if(!force&&job.status==='COMPLETE'&&job.build===build&&job.signature===signature&&job.record)return {owned:false,status:'COMPLETE',day,record:job.record};const jobData={schema:'liber.revex.report-job.v2',status:'RUNNING',runId,revision,day,signature,startedAt:new Date(at).toISOString(),leaseUntil:at+LEASE_MS,build};tx.set(ref,jobData);return {owned:true,status:'RUNNING',runId,day,ref,projectId};});}
 async function fail(lease,error){await db.runTransaction(async tx=>{const s=await tx.get(lease.ref);if(!s.exists||s.data().runId!==lease.runId)return;tx.set(lease.ref,{status:'FAILED',leaseUntil:0,failedAt:new Date(now()).toISOString(),error:String(error?.message||'Report failed.').slice(0,1800),errorCode:String(error?.code||'report-failed'),planEvidenceStatus:'INCOMPLETE'},{merge:true});});}
 async function complete(lease,record){const pointer=db.doc(`projects/${lease.projectId}/library/revex_daily_report_${lease.day}`),history=db.doc(`projects/${lease.projectId}/library/revex_daily_report_run_${lease.runId}`);return db.runTransaction(async tx=>{const [job,prior]=await Promise.all([tx.get(lease.ref),tx.get(pointer)]);if(!job.exists||job.data().runId!==lease.runId||job.data().status!=='RUNNING')throw Object.assign(new Error('A newer report attempt owns this day. Its report was retained.'),{code:'aborted'});const old=prior.exists?prior.data():{};const oldIds=new Set(old.coveredRevisions||[]),newIds=new Set(record.coveredRevisions||[]);if([...oldIds].some(id=>!newIds.has(id)))throw Object.assign(new Error('The report does not cover all previously published revisions. The previous daily report was retained.'),{code:'failed-precondition'});tx.set(history,{...record,revexKind:'daily-report-run',runId:lease.runId});tx.set(pointer,record);tx.set(lease.ref,{status:'COMPLETE',record,leaseUntil:0,completedAt:new Date(now()).toISOString(),pdfUrl:record.pdfUrl,changeCount:record.changeCount,coveredRevisions:record.coveredRevisions,planEvidenceStatus:record.planEvidenceStatus},{merge:true});return record;});}
 return {claim,fail,complete};
}
module.exports={createReportJobs};

