substitutions:
  _REGION: us-central1
  _REPOSITORY: revex
  _IMAGE: revex-energy-worker
  _TAG: 0.8.19-r49
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - server/revex-energy-worker/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}

timeout: 1800s
