using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace VRoidCloudXWear
{
    public static class Batch
    {
        private static string OutputDir { get { var v = ArgValue("-output"); return string.IsNullOrWhiteSpace(v) ? Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "CloudOutput")) : Path.GetFullPath(v); } }
        private static string InputPackage { get { return ArgValue("-sourcePackage") ?? ""; } }
        private static string LogPath { get { return Path.Combine(OutputDir, "unity_bridge.log"); } }
        private static readonly List<string> TraceLines = new List<string>();

        private static string ArgValue(string key)
        {
            string[] args = Environment.GetCommandLineArgs();
            for (int i = 0; i < args.Length - 1; i++)
                if (string.Equals(args[i], key, StringComparison.OrdinalIgnoreCase)) return args[i + 1];
            return null;
        }

        public static async void ConvertAndExport()
        {
            try
            {
                Directory.CreateDirectory(OutputDir);
                Log("CONVERT START");
                Log("Unity=" + Application.unityVersion + " | cwd=" + Directory.GetCurrentDirectory());
                Log("Source package argument=" + InputPackage);
                AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
                var importedCandidates = AssetDatabase.GetAllAssetPaths().Where(p => p.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase) && !p.StartsWith("Assets/VRoidCloudConverter", StringComparison.OrdinalIgnoreCase) && !p.StartsWith("Assets/VRoidAutoGenerated", StringComparison.OrdinalIgnoreCase)).ToArray();
                Log("Imported asset paths=" + importedCandidates.Length);
                if (importedCandidates.Length == 0)
                    throw new InvalidOperationException("No package assets are visible. The cloud runner must launch Unity with -importPackage before -executeMethod.");

                Type accessoryRootType = FindAccessoryRootType();
                if (accessoryRootType == null)
                    throw new InvalidOperationException("XWear AccessoryRootComponent was not found. XWear Packager did not load correctly.");
                Log("Accessory root type: " + accessoryRootType.FullName);

                SourceChoice source = DiscoverSource();
                Log("Chosen source: " + source.Path + " | renderers=" + source.RendererCount + " | score=" + source.Score);

                string genRoot = "Assets/VRoidAutoGenerated";
                EnsureAssetFolder(genRoot);
                EnsureAssetFolder(genRoot + "/Prepared");
                EnsureAssetFolder(genRoot + "/Materials");

                GameObject pair = BuildVariant(source.Asset, source.BaseName + "_Pair", Side.None, accessoryRootType, genRoot);
                SideMap sideMap = AnalyzeSides(pair);
                Log("Side analysis: left=" + sideMap.LeftNames.Count + " right=" + sideMap.RightNames.Count);

                var variants = new List<GameObject>();
                variants.Add(pair);
                if (sideMap.LeftNames.Count > 0 && sideMap.RightNames.Count > 0)
                {
                    variants.Add(BuildVariant(source.Asset, source.BaseName + "_Left", Side.Left, accessoryRootType, genRoot));
                    variants.Add(BuildVariant(source.Asset, source.BaseName + "_Right", Side.Right, accessoryRootType, genRoot));
                }

                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
                DumpXWearApi();

                EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
                int success = 0;
                foreach (GameObject prefab in variants)
                {
                    GameObject instance = PrefabUtility.InstantiatePrefab(prefab) as GameObject;
                    if (instance == null) instance = UnityEngine.Object.Instantiate(prefab);
                    instance.name = prefab.name;
                    instance.SetActive(true);
                    instance.transform.position = Vector3.zero;
                    instance.transform.rotation = Quaternion.identity;
                    instance.transform.localScale = Vector3.one;

                    string outPath = Path.Combine(OutputDir, SanitizeFileName(prefab.name) + ".xwear");
                    if (File.Exists(outPath)) File.Delete(outPath);
                    Log("EXPORT BEGIN: " + prefab.name + " -> " + outPath);
                    bool ok = await ExportWithDiscovery(instance, outPath, prefab.name);
                    if (ok && ValidateXWear(outPath))
                    {
                        success++;
                        Log("EXPORT OK: " + outPath);
                    }
                    else
                    {
                        Log("EXPORT FAILED: " + prefab.name);
                    }
                    UnityEngine.Object.DestroyImmediate(instance);
                }

                string result = Path.Combine(OutputDir, "RESULT.txt");
                File.WriteAllText(result,
                    "VRoid 2.14 XWear cloud conversion\r\n" +
                    "Source asset: " + source.Path + "\r\n" +
                    "Prepared variants: " + variants.Count + "\r\n" +
                    "Valid .xwear files: " + success + "\r\n" +
                    "Expected: " + variants.Count + "\r\n",
                    System.Text.Encoding.UTF8);

                FlushLog();
                if (success != variants.Count)
                {
                    throw new InvalidOperationException("Only " + success + " of " + variants.Count + " XWear files exported. See xwear_api_dump.txt and unity_bridge.log.");
                }
                Log("ALL COMPLETE");
                FlushLog();
                EditorApplication.Exit(0);
            }
            catch (Exception ex)
            {
                Log("FATAL: " + ex);
                FlushLog();
                EditorApplication.Exit(23);
            }
        }

        private enum Side { None, Left, Right }

        private sealed class SourceChoice
        {
            public string Path;
            public string BaseName;
            public GameObject Asset;
            public int RendererCount;
            public int Score;
        }

        private sealed class SideMap
        {
            public readonly HashSet<string> LeftNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            public readonly HashSet<string> RightNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        }

        private sealed class ExportCandidate
        {
            public Type Type;
            public MethodInfo Method;
            public int Score;
            public override string ToString() { return Score + " | " + Type.FullName + "." + Method.Name + Signature(Method); }
        }

        private static SourceChoice DiscoverSource()
        {
            var paths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string p in AssetDatabase.GetAllAssetPaths())
            {
                if (string.IsNullOrEmpty(p) || !p.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase)) continue;
                if ((p.StartsWith("Assets/VRoidAutoConverter", StringComparison.OrdinalIgnoreCase) || p.StartsWith("Assets/VRoidCloudConverter", StringComparison.OrdinalIgnoreCase)) || p.StartsWith("Assets/VRoidAutoGenerated", StringComparison.OrdinalIgnoreCase)) continue;
                string ext = Path.GetExtension(p).ToLowerInvariant();
                if (ext == ".fbx" || ext == ".prefab") paths.Add(p);
            }
            var all = new List<SourceChoice>();
            foreach (string p in paths)
            {
                GameObject a = AssetDatabase.LoadAssetAtPath<GameObject>(p);
                if (a == null) continue;
                int rc = a.GetComponentsInChildren<Renderer>(true).Length;
                if (rc == 0) continue;
                string baseName = Path.GetFileNameWithoutExtension(p);
                int score = rc * 5;
                if (p.EndsWith(".fbx", StringComparison.OrdinalIgnoreCase)) score += 80;
                else score += 35;
                score += Math.Max(0, 45 - baseName.Length);
                if (baseName.IndexOf('_') < 0 && baseName.IndexOf('-') < 0) score += 30;
                string low = baseName.ToLowerInvariant();
                if (low.Contains("body") || low.Contains("avatar") || low.Contains("sample") || low.Contains("demo")) score -= 80;
                if (low.Contains("marycia")) score -= 25;
                if (string.Equals(baseName, "ThreeStarPierce", StringComparison.OrdinalIgnoreCase)) score += 500;
                all.Add(new SourceChoice { Path = p, BaseName = baseName, Asset = a, RendererCount = rc, Score = score });
                Log("SOURCE CANDIDATE: " + score + " | " + rc + " renderers | " + p);
            }
            SourceChoice best = all.OrderByDescending(x => x.Score).ThenBy(x => x.Path.Length).FirstOrDefault();
            if (best == null) throw new InvalidOperationException("No renderable FBX/prefab was found in the imported package.");
            return best;
        }

        private static GameObject BuildVariant(GameObject source, string name, Side keepSide, Type accessoryRootType, string genRoot)
        {
            GameObject instance = PrefabUtility.InstantiatePrefab(source) as GameObject;
            if (instance == null) instance = UnityEngine.Object.Instantiate(source);
            instance.name = name;
            instance.SetActive(true);
            instance.transform.position = Vector3.zero;
            instance.transform.rotation = Quaternion.identity;
            instance.transform.localScale = Vector3.one;

            RepairMaterials(instance, genRoot + "/Materials");
            if (keepSide != Side.None) PruneOtherSide(instance, keepSide);

            foreach (Transform t in instance.GetComponentsInChildren<Transform>(true))
                GameObjectUtility.RemoveMonoBehavioursWithMissingScript(t.gameObject);

            Component existing = instance.GetComponent(accessoryRootType);
            if (existing == null) instance.AddComponent(accessoryRootType);

            string path = genRoot + "/Prepared/" + SanitizeFileName(name) + ".prefab";
            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(instance, path);
            UnityEngine.Object.DestroyImmediate(instance);
            if (prefab == null) throw new InvalidOperationException("Could not save prepared prefab: " + path);
            Log("PREPARED: " + path);
            return prefab;
        }

        private static void RepairMaterials(GameObject root, string materialFolder)
        {
            Shader lil = Shader.Find("lilToon");
            Shader fallback = Shader.Find("Standard");
            var cache = new Dictionary<Material, Material>();
            Material[] available = AssetDatabase.FindAssets("t:Material", new[] { "Assets" })
                .Select(g => AssetDatabase.LoadAssetAtPath<Material>(AssetDatabase.GUIDToAssetPath(g)))
                .Where(m => m != null).ToArray();

            foreach (Renderer r in root.GetComponentsInChildren<Renderer>(true))
            {
                Material[] mats = r.sharedMaterials;
                bool changed = false;
                for (int i = 0; i < mats.Length; i++)
                {
                    Material m = mats[i];
                    if (m == null)
                    {
                        Material guessed = available.FirstOrDefault(x => string.Equals(x.name, i == 0 ? "metal" : "jewel", StringComparison.OrdinalIgnoreCase));
                        if (guessed == null && available.Length > 0) guessed = available[Math.Min(i, available.Length - 1)];
                        mats[i] = guessed;
                        changed = true;
                        continue;
                    }
                    bool broken = m.shader == null || string.Equals(m.shader.name, "Hidden/InternalErrorShader", StringComparison.OrdinalIgnoreCase);
                    if (!broken) continue;
                    Material fixedMat;
                    if (!cache.TryGetValue(m, out fixedMat))
                    {
                        fixedMat = new Material(m);
                        fixedMat.name = m.name + "_VRoidFixed";
                        if (lil != null) fixedMat.shader = lil;
                        else if (fallback != null) fixedMat.shader = fallback;
                        else throw new InvalidOperationException("No usable shader found for material " + m.name);
                        string mp = materialFolder + "/" + SanitizeFileName(fixedMat.name) + ".mat";
                        AssetDatabase.CreateAsset(fixedMat, AssetDatabase.GenerateUniqueAssetPath(mp));
                        cache[m] = fixedMat;
                        Log("MATERIAL REPAIRED: " + m.name + " -> " + fixedMat.shader.name);
                    }
                    mats[i] = fixedMat;
                    changed = true;
                }
                if (changed) r.sharedMaterials = mats;
            }
        }

        private static SideMap AnalyzeSides(GameObject root)
        {
            var map = new SideMap();
            Transform[] all = root.GetComponentsInChildren<Transform>(true);
            var names = new HashSet<string>(all.Select(x => x.name), StringComparer.OrdinalIgnoreCase);
            foreach (Transform t in all)
            {
                if (t == root.transform) continue;
                Side s = ClassifySide(t.name, names);
                if (s == Side.Left) map.LeftNames.Add(t.name);
                else if (s == Side.Right) map.RightNames.Add(t.name);
            }
            return map;
        }

        private static void PruneOtherSide(GameObject root, Side keep)
        {
            SideMap map = AnalyzeSides(root);
            HashSet<string> remove = keep == Side.Left ? map.RightNames : map.LeftNames;
            Transform[] all = root.GetComponentsInChildren<Transform>(true)
                .OrderByDescending(t => Depth(t)).ToArray();
            foreach (Transform t in all)
            {
                if (t == root.transform) continue;
                if (remove.Contains(t.name)) UnityEngine.Object.DestroyImmediate(t.gameObject);
            }
            Log("SIDE PRUNE " + keep + ": removed " + remove.Count + " named side objects");
        }

        private static int Depth(Transform t) { int d = 0; while (t.parent != null) { d++; t = t.parent; } return d; }

        private static Side ClassifySide(string n, HashSet<string> names)
        {
            string[,] pairs = new string[,] {
                {"Left","Right"}, {"left","right"}, {"LEFT","RIGHT"},
                {"L_","R_"}, {"_L","_R"}, {".L",".R"}, {"-L","-R"}, {" L"," R"}
            };
            for (int i = 0; i < pairs.GetLength(0); i++)
            {
                string l = pairs[i,0], r = pairs[i,1];
                int li = n.IndexOf(l, StringComparison.Ordinal);
                if (li >= 0)
                {
                    string counterpart = n.Substring(0, li) + r + n.Substring(li + l.Length);
                    if (names.Contains(counterpart)) return Side.Left;
                }
                int ri = n.IndexOf(r, StringComparison.Ordinal);
                if (ri >= 0)
                {
                    string counterpart = n.Substring(0, ri) + l + n.Substring(ri + r.Length);
                    if (names.Contains(counterpart)) return Side.Right;
                }
            }
            return Side.None;
        }

        private static Type FindAccessoryRootType()
        {
            string exact = "XWear.IO.Runtime.Components.AccessoryRoot.AccessoryRootComponent";
            foreach (Assembly a in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type t = null;
                try { t = a.GetType(exact, false); } catch {}
                if (t != null) return t;
            }
            return AllTypes().FirstOrDefault(t => t != null && t.Name == "AccessoryRootComponent" && typeof(Component).IsAssignableFrom(t));
        }

        private static async Task<bool> ExportWithDiscovery(GameObject root, string outputPath, string itemName)
        {
            DateTime start = DateTime.UtcNow.AddSeconds(-2);
            var candidates = GetExportCandidates(root, outputPath, itemName);
            Log("EXPORT CANDIDATES: " + candidates.Count);
            int attempt = 0;
            foreach (ExportCandidate c in candidates)
            {
                attempt++;
                if (attempt > 180) break;
                try
                {
                    object target = null;
                    if (!c.Method.IsStatic)
                    {
                        target = CreateObjectForType(c.Type, root, outputPath, itemName, 0);
                        if (target == null) { Log("SKIP instance unavailable: " + c); continue; }
                        PopulateMembers(target, root, outputPath, itemName, 0);
                    }
                    object[] args;
                    if (!BuildArguments(c.Method.GetParameters(), root, outputPath, itemName, out args))
                    {
                        Log("SKIP args unsupported: " + c);
                        continue;
                    }
                    Log("TRY " + c);
                    object result = c.Method.Invoke(target, args);
                    await AwaitUnknown(result);
                    AssetDatabase.SaveAssets();
                    AssetDatabase.Refresh();
                    string found = FindProducedXWear(outputPath, start);
                    if (!string.IsNullOrEmpty(found))
                    {
                        if (!Path.GetFullPath(found).Equals(Path.GetFullPath(outputPath), StringComparison.OrdinalIgnoreCase))
                        {
                            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
                            File.Copy(found, outputPath, true);
                        }
                        if (ValidateXWear(outputPath))
                        {
                            Log("SUCCESS VIA " + c);
                            return true;
                        }
                    }
                }
                catch (TargetInvocationException tie)
                {
                    Exception inner = tie.InnerException ?? tie;
                    Log("FAIL " + c + " :: " + inner.GetType().Name + ": " + inner.Message);
                }
                catch (Exception ex)
                {
                    Log("FAIL " + c + " :: " + ex.GetType().Name + ": " + ex.Message);
                }
            }
            return false;
        }

        private static List<ExportCandidate> GetExportCandidates(GameObject root, string outputPath, string itemName)
        {
            var list = new List<ExportCandidate>();
            BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance;
            foreach (Type t in AllTypes())
            {
                if (t == null) continue;
                string tn = (t.FullName ?? t.Name);
                string an = t.Assembly.GetName().Name ?? "";
                if (tn.IndexOf("XWear", StringComparison.OrdinalIgnoreCase) < 0 && an.IndexOf("XWear", StringComparison.OrdinalIgnoreCase) < 0) continue;
                MethodInfo[] methods;
                try { methods = t.GetMethods(flags); } catch { continue; }
                foreach (MethodInfo m in methods)
                {
                    if (m.IsSpecialName || m.ContainsGenericParameters || m.IsAbstract) continue;
                    string mn = m.Name.ToLowerInvariant();
                    if (!mn.Contains("export")) continue;
                    if (mn.Contains("import")) continue;
                    ParameterInfo[] ps = m.GetParameters();
                    if (ps.Length > 12) continue;
                    int score = 0;
                    if (mn == "export" || mn == "exportasync") score += 90;
                    if (mn.Contains("xwear")) score += 90;
                    if (mn.Contains("execute")) score += 25;
                    string tl = tn.ToLowerInvariant();
                    if (tl.Contains("exporter")) score += 70;
                    if (tl.Contains("export")) score += 35;
                    if (tl.Contains("xwear")) score += 30;
                    if (m.IsStatic) score += 20;
                    if (ps.Any(p => typeof(GameObject).IsAssignableFrom(UnwrapByRef(p.ParameterType)) || typeof(Transform).IsAssignableFrom(UnwrapByRef(p.ParameterType)))) score += 70;
                    if (ps.Any(p => UnwrapByRef(p.ParameterType) == typeof(string) && IsPathName(p.Name))) score += 65;
                    if (ps.Length <= 6) score += 20;
                    if (typeof(EditorWindow).IsAssignableFrom(t)) score -= 35;
                    if (mn.Contains("menu") || mn.Contains("validate") || mn.Contains("ongui")) score -= 100;
                    list.Add(new ExportCandidate { Type = t, Method = m, Score = score });
                }
            }
            return list.OrderByDescending(x => x.Score).ThenBy(x => x.Method.GetParameters().Length).ToList();
        }

        private static bool BuildArguments(ParameterInfo[] ps, GameObject root, string path, string itemName, out object[] args)
        {
            args = new object[ps.Length];
            for (int i = 0; i < ps.Length; i++)
            {
                object v;
                if (!TryBuildValue(UnwrapByRef(ps[i].ParameterType), ps[i].Name, root, path, itemName, 0, out v))
                {
                    if (ps[i].HasDefaultValue) v = ps[i].DefaultValue;
                    else return false;
                }
                args[i] = v;
            }
            return true;
        }

        private static bool TryBuildValue(Type t, string memberName, GameObject root, string path, string itemName, int depth, out object value)
        {
            value = null;
            string n = (memberName ?? "").ToLowerInvariant();
            if (t == typeof(string))
            {
                if (IsPathName(memberName)) value = path;
                else if (n.Contains("creator") || n.Contains("author")) value = "";
                else if (n.Contains("license") || n.Contains("url")) value = "";
                else if (n.Contains("format") || n.Contains("extension")) value = ".xwear";
                else value = itemName;
                return true;
            }
            if (t == typeof(GameObject) || t.IsAssignableFrom(typeof(GameObject))) { value = root; return true; }
            if (t == typeof(Transform) || t.IsAssignableFrom(typeof(Transform))) { value = root.transform; return true; }
            if (typeof(Component).IsAssignableFrom(t))
            {
                Component c = root.GetComponent(t);
                if (c != null) { value = c; return true; }
                return false;
            }
            if (t == typeof(UnityEngine.Object)) { value = root; return true; }
            if (t == typeof(bool)) { value = n.Contains("accessory") || n.Contains("active") || n.Contains("include") || n.Contains("enable"); return true; }
            if (t == typeof(int)) { value = 0; return true; }
            if (t == typeof(float)) { value = 0f; return true; }
            if (t == typeof(double)) { value = 0d; return true; }
            if (t == typeof(CancellationToken)) { value = CancellationToken.None; return true; }
            if (t.IsEnum)
            {
                Array vals = Enum.GetValues(t);
                foreach (object x in vals)
                {
                    string s = x.ToString().ToLowerInvariant();
                    if (s.Contains("xwear") || s.Contains("accessory") || s == "wear") { value = x; return true; }
                }
                value = vals.Length > 0 ? vals.GetValue(0) : Activator.CreateInstance(t);
                return true;
            }
            Type nullable = Nullable.GetUnderlyingType(t);
            if (nullable != null) return TryBuildValue(nullable, memberName, root, path, itemName, depth, out value);
            if (t.IsArray)
            {
                Type e = t.GetElementType();
                object one;
                if (TryBuildValue(e, memberName, root, path, itemName, depth + 1, out one))
                {
                    Array a = Array.CreateInstance(e, 1); a.SetValue(one, 0); value = a; return true;
                }
                value = Array.CreateInstance(e, 0); return true;
            }
            if (t.IsGenericType && typeof(IList).IsAssignableFrom(t))
            {
                try
                {
                    IList list = (IList)Activator.CreateInstance(t);
                    Type e = t.GetGenericArguments()[0]; object one;
                    if (TryBuildValue(e, memberName, root, path, itemName, depth + 1, out one)) list.Add(one);
                    value = list; return true;
                } catch { return false; }
            }
            if (typeof(Delegate).IsAssignableFrom(t)) { value = null; return true; }
            if (t.IsValueType)
            {
                value = Activator.CreateInstance(t);
                if (depth < 2) PopulateMembers(value, root, path, itemName, depth + 1);
                return true;
            }
            if (depth >= 2) return false;
            object o = CreateObjectForType(t, root, path, itemName, depth + 1);
            if (o == null) return false;
            PopulateMembers(o, root, path, itemName, depth + 1);
            value = o;
            return true;
        }

        private static object CreateObjectForType(Type t, GameObject root, string path, string itemName, int depth)
        {
            try
            {
                PropertyInfo singletonProp = t.GetProperty("Instance", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
                    ?? t.GetProperty("instance", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                if (singletonProp != null && t.IsAssignableFrom(singletonProp.PropertyType))
                {
                    object singleton = singletonProp.GetValue(null, null);
                    if (singleton != null) return singleton;
                }
                FieldInfo singletonField = t.GetField("Instance", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
                    ?? t.GetField("instance", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                if (singletonField != null && t.IsAssignableFrom(singletonField.FieldType))
                {
                    object singleton = singletonField.GetValue(null);
                    if (singleton != null) return singleton;
                }
                if (typeof(EditorWindow).IsAssignableFrom(t)) return ScriptableObject.CreateInstance(t);
                if (typeof(ScriptableObject).IsAssignableFrom(t)) return ScriptableObject.CreateInstance(t);
                if (t.IsAbstract || t.IsInterface) return null;
                ConstructorInfo ctor = t.GetConstructor(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, null, Type.EmptyTypes, null);
                if (ctor != null) return ctor.Invoke(null);
            } catch {}
            return null;
        }

        private static void PopulateMembers(object o, GameObject root, string path, string itemName, int depth)
        {
            if (o == null || depth > 2) return;
            Type t = o.GetType();
            BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;
            foreach (FieldInfo f in t.GetFields(flags))
            {
                if (f.IsInitOnly || f.IsLiteral) continue;
                if (!RelevantMember(f.Name, f.FieldType)) continue;
                object v;
                if (TryBuildValue(f.FieldType, f.Name, root, path, itemName, depth, out v))
                    try { f.SetValue(o, v); } catch {}
            }
            foreach (PropertyInfo p in t.GetProperties(flags))
            {
                if (!p.CanWrite || p.GetIndexParameters().Length != 0) continue;
                MethodInfo set = p.GetSetMethod(true); if (set == null) continue;
                if (!RelevantMember(p.Name, p.PropertyType)) continue;
                object v;
                if (TryBuildValue(p.PropertyType, p.Name, root, path, itemName, depth, out v))
                    try { p.SetValue(o, v, null); } catch {}
            }
        }

        private static bool RelevantMember(string name, Type t)
        {
            string n = (name ?? "").ToLowerInvariant();
            if (n.Contains("target") || n.Contains("root") || n.Contains("gameobject") || n.Contains("export") || n.Contains("path") || n.Contains("file") || n.Contains("format") || n.Contains("item") || n.Contains("name") || n.Contains("creator") || n.Contains("author") || n.Contains("license") || n.Contains("url") || n.Contains("accessory")) return true;
            if (t == typeof(GameObject) || t == typeof(Transform)) return true;
            return false;
        }

        private static bool IsPathName(string name)
        {
            string n = (name ?? "").ToLowerInvariant();
            return n.Contains("path") || n.Contains("file") || n.Contains("destination") || n.Contains("output") || n.Contains("save");
        }

        private static Type UnwrapByRef(Type t) { return t.IsByRef ? t.GetElementType() : t; }

        private static async Task AwaitUnknown(object result)
        {
            if (result == null) return;
            Task task = result as Task;
            if (task != null) { await task; return; }
            Type rt = result.GetType();
            MethodInfo getAwaiter = rt.GetMethod("GetAwaiter", BindingFlags.Public | BindingFlags.Instance, null, Type.EmptyTypes, null);
            if (getAwaiter == null) return;
            object awaiter = getAwaiter.Invoke(result, null);
            if (awaiter == null) return;
            Type at = awaiter.GetType();
            PropertyInfo doneProp = at.GetProperty("IsCompleted", BindingFlags.Public | BindingFlags.Instance);
            bool done = doneProp != null && (bool)doneProp.GetValue(awaiter, null);
            if (!done)
            {
                var tcs = new TaskCompletionSource<bool>();
                MethodInfo onCompleted = at.GetMethod("OnCompleted", BindingFlags.Public | BindingFlags.Instance, null, new[] { typeof(Action) }, null)
                    ?? at.GetMethod("UnsafeOnCompleted", BindingFlags.Public | BindingFlags.Instance, null, new[] { typeof(Action) }, null);
                if (onCompleted == null) throw new InvalidOperationException("Awaitable result has no OnCompleted: " + rt.FullName);
                onCompleted.Invoke(awaiter, new object[] { new Action(() => tcs.TrySetResult(true)) });
                await tcs.Task;
            }
            MethodInfo getResult = at.GetMethod("GetResult", BindingFlags.Public | BindingFlags.Instance, null, Type.EmptyTypes, null);
            if (getResult != null) getResult.Invoke(awaiter, null);
        }

        private static string FindProducedXWear(string expected, DateTime start)
        {
            if (File.Exists(expected) && new FileInfo(expected).Length > 32) return expected;
            var roots = new[] { OutputDir, Directory.GetCurrentDirectory() };
            string newest = null; DateTime newestTime = DateTime.MinValue;
            foreach (string r in roots.Distinct())
            {
                if (string.IsNullOrEmpty(r) || !Directory.Exists(r)) continue;
                try
                {
                    foreach (string f in Directory.GetFiles(r, "*.xwear", SearchOption.AllDirectories))
                    {
                        DateTime t = File.GetLastWriteTimeUtc(f);
                        if (t >= start && t > newestTime) { newest = f; newestTime = t; }
                    }
                } catch {}
            }
            return newest;
        }

        private static bool ValidateXWear(string path)
        {
            try
            {
                if (!File.Exists(path) || new FileInfo(path).Length < 128) return false;
                using (FileStream fs = File.OpenRead(path))
                using (ZipArchive z = new ZipArchive(fs, ZipArchiveMode.Read))
                {
                    bool xitem = z.Entries.Any(e => e.FullName.Replace('\\','/').EndsWith("XItem.json", StringComparison.OrdinalIgnoreCase));
                    return xitem && z.Entries.Count >= 2;
                }
            }
            catch { return false; }
        }

        private static void DumpXWearApi()
        {
            try
            {
                var lines = new List<string>();
                foreach (Type t in AllTypes().Where(t => t != null && ((t.FullName ?? "").IndexOf("XWear", StringComparison.OrdinalIgnoreCase) >= 0 || (t.Assembly.GetName().Name ?? "").IndexOf("XWear", StringComparison.OrdinalIgnoreCase) >= 0)).OrderBy(t => t.FullName))
                {
                    lines.Add("TYPE " + t.Assembly.GetName().Name + " :: " + t.FullName);
                    MethodInfo[] ms; try { ms = t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance | BindingFlags.DeclaredOnly); } catch { continue; }
                    foreach (MethodInfo m in ms.OrderBy(m => m.Name))
                    {
                        if (m.IsSpecialName) continue;
                        string low = m.Name.ToLowerInvariant();
                        if (low.Contains("export") || low.Contains("save") || low.Contains("archive") || low.Contains("pack")) lines.Add("  " + (m.IsStatic ? "static " : "") + m.ReturnType.FullName + " " + m.Name + Signature(m));
                    }
                }
                File.WriteAllLines(Path.Combine(OutputDir, "xwear_api_dump.txt"), lines.ToArray());
            }
            catch (Exception ex) { Log("API DUMP FAILED: " + ex.Message); }
        }

        private static IEnumerable<Type> AllTypes()
        {
            foreach (Assembly a in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] ts;
                try { ts = a.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { ts = ex.Types; }
                catch { continue; }
                foreach (Type t in ts) if (t != null) yield return t;
            }
        }

        private static string Signature(MethodInfo m)
        {
            try { return "(" + string.Join(", ", m.GetParameters().Select(p => (p.ParameterType.FullName ?? p.ParameterType.Name) + " " + p.Name).ToArray()) + ")"; }
            catch { return "(?)"; }
        }

        private static string SanitizeFileName(string s)
        {
            foreach (char c in Path.GetInvalidFileNameChars()) s = s.Replace(c, '_');
            return s;
        }

        private static void EnsureAssetFolder(string assetPath)
        {
            if (AssetDatabase.IsValidFolder(assetPath)) return;
            string parent = Path.GetDirectoryName(assetPath).Replace('\\','/');
            string leaf = Path.GetFileName(assetPath);
            if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent)) EnsureAssetFolder(parent);
            if (!AssetDatabase.IsValidFolder(assetPath)) AssetDatabase.CreateFolder(parent, leaf);
        }

        private static void Log(string line)
        {
            string s = DateTime.UtcNow.ToString("o") + " " + line;
            TraceLines.Add(s);
            Debug.Log("[VRoidCloudXWear] " + line);
        }

        private static void FlushLog()
        {
            try
            {
                Directory.CreateDirectory(OutputDir);
                File.WriteAllLines(LogPath, TraceLines.ToArray());
            }
            catch {}
        }
    }
}
