const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const origin='https://liberpict.com',preview=process.env.REVEX_PREVIEW_URL,fixture=JSON.parse(fs.readFileSync('/workspace/qa-private/accounts.json')),project='liber_qa_r183_model_a_20260904',out='/workspace/results/assets';
fs.mkdirSync(out,{recursive:true});const checks=[],errors=[];let browser,page,savedId;
const pass=(name,evidence)=>{checks.push({name,status:'PASS',evidence});console.log('ASSET_PASS '+name);};
async function overlays(){for(let i=0;i<4;i++){const g=page.getByRole('button',{name:'Got it',exact:true});if(await g.count()&&await g.last().isVisible())await g.last().click();else break;}if(await page.locator('#revex-install-close').isVisible())await page.locator('#revex-install-close').click();}
(async()=>{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:960}});await context.addInitScript(()=>{try{navigator.serviceWorker.register=async()=>undefined;}catch{}});
 await context.route(origin+'/liber-apps/**',async r=>{if(r.request().method()!=='GET')return r.continue();const u=new URL(r.request().url());await r.fulfill({response:await r.fetch({url:preview+u.pathname+u.search})});});page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/liber-apps/index.html#apps');await page.waitForFunction(()=>window.firebaseService?._authStateReady&&window.authManager);await page.locator('#loginUsername').fill(fixture.accounts[0].email);await page.locator('#loginPassword').fill(fixture.accounts[0].password);await page.locator('#loginForm button[type=submit]').click();await page.waitForFunction(uid=>firebaseService.auth.currentUser?.uid===uid&&authManager.currentUser?.id===uid,fixture.accounts[0].uid);
 await page.evaluate(async({id,uid,qa})=>{const s=firebaseService,a=s.firebase,r=await a.getDoc(a.doc(s.db,'projects',id));if(!r.exists()||r.data().ownerId!==uid||r.data().qaFixture!==qa)throw Error('QA ownership mismatch');},{id:project,uid:fixture.accounts[0].uid,qa:fixture.fixtureId});
 const open=async()=>{await page.goto(origin+'/liber-apps/apps/revex/index.html?projectId='+project+'&view=bim');await page.waitForFunction(()=>window.__revexViewerR26Instance?.detailLoaded&&document.getElementById('browser-assets'),null,{timeout:120000});await overlays();};await open();
 await page.locator('#revex-r157-assets-open').click();
 const formats=await page.evaluate(async()=>{
  const T=await import('three'),a=await import('./asset-import.js?v=20260928r201-audit3'),f=await import('https://cdn.jsdelivr.net/npm/fflate@0.8.2/esm/browser.js');const canvas=document.createElement('canvas');canvas.width=canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);const mesh=new T.Mesh(new T.BoxGeometry(1,.75,.6),new T.MeshStandardMaterial({color:0xff2b80,map:new T.CanvasTexture(canvas)}));window.qaAsset=await a.exportAsset(mesh);const glb=await a.importAsset([qaAsset]);let textured=false;glb.root.traverse(n=>{if(n.material?.map?.image?.width)textured=true;});if(!textured)throw Error('Embedded model texture was lost');a.disposeAsset(glb.root);
  const obj='mtllib cube.mtl\nv 0 0 0\nv 1000 0 0\nv 0 750 0\nusemtl oak\nf 1 2 3\n';const parsed=await a.importAsset([new File([obj],'cube.obj'),new File(['newmtl oak\nKd 0.8 0.4 0.2\n'],'cube.mtl')]);const dimensions=new T.Box3().setFromObject(parsed.root).getSize(new T.Vector3()).toArray();a.disposeAsset(parsed.root);
  const zip=await a.importAsset([new File([f.zipSync({'asset.glb':new Uint8Array(await qaAsset.arrayBuffer())})],'model.zip')]);a.disposeAsset(zip.root);
  let unsupported=false;try{await a.importAsset([new File(['RFA'],'family.rfa')]);}catch(e){unsupported=e.message.includes('Revit-only');}if(!unsupported)throw Error('RFA falsely accepted');
  const stl=await a.importAsset([new File(['solid test\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 1000 0 0\nvertex 0 750 0\nendloop\nendfacet\nendsolid test'],'test.stl')]);a.disposeAsset(stl.root);
  return {glb:true,obj:dimensions,zip:true,stl:true,rfaExplicit:true};
 });pass('Actual GLB, OBJ/material, ZIP and STL parsers open geometry; RFA has a clear conversion message',formats);
 for(const [name,url] of [['test.ifc','https://raw.githubusercontent.com/ThatOpen/engine_web-ifc/main/examples/example.ifc'],['vCube.fbx','https://raw.githubusercontent.com/mrdoob/three.js/r179/examples/models/fbx/vCube.fbx']]){
  const r=await fetch(url);assert(r.ok);const bytes=Array.from(new Uint8Array(await r.arrayBuffer()));const result=await page.evaluate(async({name,bytes})=>{const a=await import('./asset-import.js?v=20260928r201-audit3'),p=await a.importAsset([new File([new Uint8Array(bytes)],name)]);const answer={name,vertices:p.vertices,units:p.units};a.disposeAsset(p.root);return answer;},{name,bytes});assert(result.vertices>0);pass('Official '+name+' fixture opens through the browser importer',result);
 }
 await page.evaluate(async()=>{const v=__revexViewerR26Instance;v.floor=12;v.camera.position.set(10,17.5,20);v.camera.lookAt(10,17.5,0);v.camera.updateMatrixWorld(true);v.walk=true;await RevexWebAssets.stage([qaAsset]);});await page.locator('#browser-asset-preview').waitFor({state:'visible'});
 const position=await page.evaluate(async()=>{const T=await import('three'),v=__revexViewerR26Instance,g=v.scene.getObjectByName('REVEX_ASSET_PREVIEW'),box=new T.Box3().setFromObject(g);v.walk=false;return {position:g.position.toArray(),min:box.min.toArray(),size:box.getSize(new T.Vector3()).toArray()};});assert(Math.abs(position.min[1]-12)<.00001);assert.deepEqual(position.position,[10,12,14]);assert(Math.abs(position.size[0]-1/.3048)<.0001);pass('Preview lands six feet ahead on the active floor with correct metre-to-foot scale',position);
 await page.locator('#browser-asset-rotation').fill('90');await page.locator('#browser-asset-x').fill('1.5');await page.locator('#browser-asset-save').click();await page.locator('#browser-asset-status').filter({hasText:'Placed in this REVEX project'}).waitFor();await page.waitForFunction(()=>[...RevexWebAssets.placed.values()].some(x=>!x.pending));savedId=await page.evaluate(()=>[...RevexWebAssets.placed.keys()].at(-1));assert(savedId);await page.screenshot({path:out+'/asset-saved-desktop.png'});
 await open();await page.waitForFunction(id=>RevexWebAssets.placed.get(id)&&!RevexWebAssets.placed.get(id).pending,savedId);const restored=await page.evaluate(async id=>{const T=await import('three'),g=RevexWebAssets.placed.get(id).group;return {position:g.position.toArray(),rotation:g.rotation.y,minY:new T.Box3().setFromObject(g).min.y};},savedId);assert.deepEqual(restored.position,[11.5,12,14]);assert(Math.abs(restored.rotation-Math.PI/2)<1e-6);assert(Math.abs(restored.minY-12)<1e-6);pass('Real cloud upload, placement, rotation and floor survive a full page reload',restored);
 await page.locator('#revex-r157-assets-open').click();await page.locator('#browser-assets summary').click();await page.locator('[data-asset-copy="'+savedId+'"]').click();await page.locator('#browser-asset-preview').waitFor({state:'visible'});assert.match(await page.locator('#browser-asset-status').innerText(),/Preview ready/);await page.evaluate(async()=>{window.qaAsset=await (await import('./asset-import.js?v=20260928r201-audit3')).exportAsset(__revexViewerR26Instance.scene.getObjectByName('REVEX_ASSET_PREVIEW').children[0]);});await page.locator('#browser-asset-cancel').click();pass('Saved model can be reused without a new source download or conversion');await page.locator('[data-asset-remove="'+savedId+'"]').click();await page.waitForFunction(id=>!RevexWebAssets.placed.has(id),savedId);pass('Removing a saved placement updates both scene and cloud list');
 await page.evaluate(()=>{window.qaDownload=null;window.showDirectoryPicker=async()=>({async *values(){if(qaDownload)yield {kind:'file',name:'download.glb',getFile:async()=>qaDownload};}});});await page.locator('#browser-asset-watch').click();await page.evaluate(()=>{window.qaDownload=new File([qaAsset],'download.glb',{lastModified:Date.now()+50});});await page.locator('#browser-asset-preview').waitFor({state:'visible',timeout:15000});assert.match(await page.locator('#browser-asset-status').innerText(),/Preview ready/);assert.equal(await page.evaluate(()=>RevexWebAssets.placed.size),0);await page.locator('#browser-asset-cancel').click();await page.locator('#browser-asset-watch').click();pass('Connected download-folder handler captures a stable new model as an unsaved preview');
 await page.evaluate(async()=>{window.qaReleaseRead=null;const file=new File([qaAsset],'delayed.glb');file.arrayBuffer=()=>new Promise(resolve=>{window.qaReleaseRead=async()=>resolve(await qaAsset.arrayBuffer());});window.qaPendingStage=RevexWebAssets.stage([file]);});await page.waitForFunction(()=>Boolean(window.qaReleaseRead));await page.evaluate(async()=>{__revexState.activationToken++;dispatchEvent(new CustomEvent('revex:project-boundary'));await new Promise(r=>setTimeout(r,50));await qaReleaseRead();await qaPendingStage;});assert(await page.locator('#browser-asset-preview').isHidden());assert(!await page.evaluate(()=>Boolean(__revexViewerR26Instance.scene.getObjectByName('REVEX_ASSET_PREVIEW'))));pass('An import completing after a project boundary cannot leak a preview into the new context');
 await page.locator('.r157-assets-close').click();await page.locator('#revex-wallt-open').click();assert.equal(await page.locator('#revex-wallt-open').textContent(),'✦');await page.locator('[data-mode=fixer]').click();await page.locator('[data-fix=fit]').click();assert.match(await page.locator('#revex-wallt-status').innerText(),/reset/);await page.locator('[data-mode=helper]').click();await page.locator('#revex-wallt-question').fill('Explain the available actions in the current view.');await page.locator('#revex-wallt-ask').click();await page.locator('#revex-wallt-answer').filter({hasText:/\S/}).waitFor({timeout:85000});pass('Restored star helper/fixer performs a real view repair and receives a live WALLT answer');await page.screenshot({path:out+'/wallt-desktop.png'});await page.locator('#revex-wallt-dialog [data-close]').click();
 // Check viewport containment in short, narrow, tablet and wide layouts.
 for(const [width,height]of [[320,568],[390,844],[768,1024],[1024,600],[1440,900],[1920,1080],[844,390]]){
  await page.setViewportSize({width,height});await page.evaluate(()=>{const d=document.getElementById('revex-wallt-dialog');if(!d.open)d.show();});const wall=await page.locator('#revex-wallt-dialog').boundingBox();assert(wall.x>=-1&&wall.y>=-1&&wall.x+wall.width<=width+1&&wall.y+wall.height<=height+1,JSON.stringify({width,height,wall}));await page.screenshot({path:out+`/wallt-${width}x${height}.png`});await page.locator('#revex-wallt-dialog [data-close]').click();
  await page.evaluate(()=>{document.getElementById('revex-r157-assets-panel').hidden=false;});const box=await page.locator('#revex-r157-assets-panel').boundingBox();assert(box.x>=-1&&box.y>=-1&&box.x+box.width<=width+1&&box.y+box.height<=height+1,JSON.stringify({width,height,box}));const overflow=await page.locator('#revex-r157-assets-panel').evaluate(e=>e.scrollWidth-e.clientWidth);assert(overflow<=1,'Asset panel horizontal overflow '+overflow);await page.screenshot({path:out+`/assets-${width}x${height}.png`});await page.evaluate(async()=>RevexWebAssets.stage([qaAsset]));const compact=await page.locator('#revex-r157-assets-panel').boundingBox();assert(compact.x>=-1&&compact.y>=-1&&compact.x+compact.width<=width+1&&compact.y+compact.height<=height+1,JSON.stringify({width,height,compact}));assert(await page.locator('#browser-asset-preview').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:out+'/placement-'+width+'x'+height+'.png'});await page.locator('#browser-asset-cancel').click();await page.locator('.r157-assets-close').click();assert(await page.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'Page overflow '+width);
 }pass('WALLT and asset controls stay inside their containers at seven screen proportions');
 await page.setViewportSize({width:1440,height:960});await page.locator('[data-view=design]').click();await page.locator('.design-card').first().click();await page.evaluate(()=>dispatchEvent(new CustomEvent('revex:source-products')));await page.locator('#design-sourcing-brief').fill('24 inch white bathroom vanity with sink, under $900, buy online with shipping to New York City');await page.locator('#design-product-sourcing [data-research]').click();await page.locator('#design-product-sourcing [data-status]').filter({hasText:/product links|could not confirm|failed|unavailable/}).waitFor({timeout:85000});const sourcing={status:await page.locator('#design-product-sourcing [data-status]').innerText(),links:await page.locator('.sourcing-products a').evaluateAll(ns=>ns.map(n=>n.href))};assert(sourcing.links.length>0,JSON.stringify(sourcing));assert(sourcing.links.every(u=>!u.includes('vertexaisearch.cloud.google.com')));await page.screenshot({path:out+'/nyc-products.png'});pass('Live grounded sourcing returns direct product-ordering links with explicit NYC delivery status',sourcing);
})().catch(async e=>{checks.push({name:'Asset and helper audit',status:'FAIL',error:e.message,stack:e.stack});console.error(e.message);await page?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(errors.length)process.exitCode=1;fs.writeFileSync(out+'/result.json',JSON.stringify({preview,checks,errors,savedId},null,2));fs.writeFileSync(out+'/exit-status.txt',String(process.exitCode||0));});


