const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const origin='https://liberpict.com',preview=process.env.REVEX_PREVIEW_URL,fixture=JSON.parse(fs.readFileSync('/workspace/qa-private/accounts.json')),projectId='release-evidence-95f5bfa7f67a539d',out='/workspace/results/audit';
fs.mkdirSync(out,{recursive:true});const checks=[],errors=[];let browser,page;
const pass=(name,evidence)=>{checks.push({name,status:'PASS',evidence});console.log('AUDIT_PASS '+name);};
(async()=>{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:960}});await context.addInitScript(()=>{try{navigator.serviceWorker.register=async()=>undefined;}catch{}});
 await context.route(origin+'/liber-apps/**',async r=>{if(r.request().method()!=='GET')return r.continue();const u=new URL(r.request().url());await r.fulfill({response:await r.fetch({url:preview+u.pathname+u.search})});});
 page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/liber-apps/index.html#apps');await page.waitForFunction(()=>window.firebaseService?._authStateReady&&window.authManager);await page.locator('#loginUsername').fill(fixture.accounts[0].email);await page.locator('#loginPassword').fill(fixture.accounts[0].password);await page.locator('#loginForm button[type="submit"]').click();await page.waitForFunction(uid=>firebaseService.auth.currentUser?.uid===uid&&authManager.currentUser?.id===uid,fixture.accounts[0].uid);
 await page.evaluate(async({id,uid,qa})=>{const s=firebaseService,a=s.firebase,r=await a.getDoc(a.doc(s.db,'projects',id));if(!r.exists()||r.data().ownerId!==uid||r.data().qaFixture!==qa)throw Error('QA ownership mismatch');},{id:projectId,uid:fixture.accounts[0].uid,qa:fixture.fixtureId});
 await page.goto(origin+'/liber-apps/apps/revex/index.html?projectId='+projectId+'&view=bim');await page.waitForFunction(()=>window.__revexViewerR26Instance?.detailLoaded&&__revexViewerR26Instance.measurement,null,{timeout:180000});
 for(let i=0;i<4;i++){const got=page.getByRole('button',{name:'Got it',exact:true});if(await got.count()&&await got.last().isVisible())await got.last().click();else break;}if(await page.locator('#revex-install-close').isVisible())await page.locator('#revex-install-close').click();
 const targets=await page.evaluate(async()=>{const T=await import('three'),v=__revexViewerR26Instance,r=v.renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster(),hits=[];v.scene.updateMatrixWorld(true);for(let y=-.6;y<=.6;y+=.12)for(let x=-.6;x<=.6;x+=.12){ray.setFromCamera(new T.Vector2(x,y),v.camera);const hit=ray.intersectObject(v.model,true).find(h=>h.object.isMesh&&!h.object.name.startsWith('REVEX_PROXY_')&&h.object.visible);if(hit)hits.push({x:r.left+(x+1)*r.width/2,y:r.top+(1-y)*r.height/2,point:hit.point.toArray()});}if(hits.length<2)throw Error('No visible full-model measurement targets');return[hits[0],hits.at(-1)];});
 await page.locator('#measure-toggle').click();for(const p of targets)await page.mouse.click(p.x,p.y);
 const measured=await page.evaluate(()=>({distance:__revexViewerR26Instance.measurement.state.distanceFeet,text:document.querySelector('.bim-measure-panel output').textContent,points:__revexViewerR26Instance.measurement.state.points.map(p=>p.toArray())}));
 assert(measured.distance>0);assert(measured.text.includes('straight-line distance'));await page.screenshot({path:out+'/bim-measure-desktop.png'});pass('Two actual points on the full native building produce a visible distance',measured);
 await page.locator('[data-measure-clear]').click();assert.equal(await page.evaluate(()=>__revexViewerR26Instance.measurement.state.points.length),0);
 const canvas=await page.locator('#viewer canvas').boundingBox();await page.mouse.move(canvas.x+canvas.width/2,canvas.y+canvas.height/2);await page.mouse.down();await page.mouse.move(canvas.x+canvas.width/2+45,canvas.y+canvas.height/2+30,{steps:6});await page.mouse.up();assert.equal(await page.evaluate(()=>__revexViewerR26Instance.measurement.state.points.length),0);pass('Orbit dragging does not add a measurement point');
 await page.keyboard.press('Escape');assert.equal(await page.locator('#measure-toggle').getAttribute('aria-pressed'),'false');
 // A known 8-foot span verifies the viewer's internal feet and metric conversion.
 const known=await page.evaluate(async()=>{const T=await import('three'),v=__revexViewerR26Instance;window.qaOriginalModel=v.model;v.model.visible=false;v.model=new T.Mesh(new T.BoxGeometry(12,12,2),new T.MeshBasicMaterial({color:0xaaaaaa}));v.scene.add(v.model);v.camera.position.set(0,0,30);v.camera.lookAt(0,0,0);v.controls.target.set(0,0,0);v.camera.updateMatrixWorld(true);v.requestRender();const r=v.renderer.domElement.getBoundingClientRect();return[-4,4].map(x=>{const p=new T.Vector3(x,0,1).project(v.camera);return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};});});
 await page.locator('#measure-toggle').click();for(const p of known)await page.mouse.click(p.x,p.y);const feet=await page.evaluate(()=>__revexViewerR26Instance.measurement.state.distanceFeet);assert(Math.abs(feet-8)<.05,'Screen-pixel selection tolerance: '+feet);assert((await page.locator('.bim-measure-panel output').innerText()).includes((feet*.3048).toFixed(3)+' m'));assert.equal(await page.evaluate(async()=> (await import('./bim-measure.js?v=20260928r201-audit3')).formatDistance(8)), '8′ 0″ · 2.438 m');pass('Known eight-foot span is within one screen pixel; unit conversion is exact',{feet});
 await page.evaluate(()=>{const v=__revexViewerR26Instance;v.measurement.clear();v.measurement.setActive(false);v.scene.remove(v.model);v.model.geometry.dispose();v.model.material.dispose();v.model=qaOriginalModel;v.model.visible=true;v.fit();});
 await page.locator('#element-tree [data-element-id]').first().click();await page.locator('#bim-inspector .r85-knob').waitFor();for(const width of [1440,1024,390,320]){await page.setViewportSize({width,height:844});if(width<861)await page.locator('#revex-r142-sheet-b').click();const bounds=await page.locator('#bim-inspector .r85-section-sliders').evaluate(e=>{const box=e.getBoundingClientRect();return [...e.querySelectorAll('input,.r85-knob')].map(n=>{const r=n.getBoundingClientRect();return {left:r.left-box.left,right:box.right-r.right,width:r.width};});});assert(bounds.every(b=>b.left>=-1&&b.right>=-1&&b.width>10),JSON.stringify({width,bounds}));await page.screenshot({path:out+'/inspector-'+width+'.png'});if(width<861)await page.locator('#revex-r142-sheet-close').click();}pass('Element XYZ and yaw controls remain inside the inspector at desktop, narrow and mobile widths');
 await page.setViewportSize({width:390,height:844});await page.locator('#measure-toggle').waitFor({state:'visible'});await page.locator('#measure-toggle').click();await page.screenshot({path:out+'/bim-measure-mobile.png'});assert((await page.locator('#measure-toggle').boundingBox()).x>=0);await page.keyboard.press('Escape');pass('Measure remains available on a 390px mobile screen');
 await page.setViewportSize({width:1440,height:960});await page.locator('[data-view="design"]').click();await page.locator('#chapter-list > [data-chapter]').first().waitFor();
 const design=await page.evaluate(()=>({numeric:__revexState.designData.chapters.filter(c=>/^\p{N}+$/u.test(c.title.normalize('NFKC').trim())).map(c=>c.id),sourceCount:__revexState.designData.chapters.length,visible:[...document.querySelectorAll('#chapter-list [data-chapter]')].map(e=>e.dataset.chapter),context:RevexDesignContext.positions().map(p=>p.chapterId)}));
 assert(design.numeric.length>0);assert(design.numeric.every(id=>!design.visible.includes(id)&&!design.context.includes(id)));await page.locator('#design-search').fill('723');assert((await page.locator('.design-card').evaluateAll(ns=>ns.map(n=>n.dataset.chapter))).every(id=>!design.numeric.includes(id))); await page.locator('#design-search').fill('');pass('Numeric-only spaces are absent from the rail, global search and Design context; original source remains intact',{hidden:design.numeric.length,retainedSourceCount:design.sourceCount});
 await page.locator('.design-card').first().click();await page.locator('[data-position-versions] summary').waitFor();assert.equal(await page.locator('[data-position-versions]').evaluate(e=>e.open),false);await page.locator('[data-position-versions] summary').click();assert.equal(await page.locator('[data-position-versions]').evaluate(e=>e.open),true);await page.locator('[data-position-versions] summary').click();await page.screenshot({path:out+'/design-book-desktop.png'});pass('Edit history opens on demand and stays collapsed by default');
 // Use local storage fixtures to exercise realtime section replacement without customer writes.
 const specContext=await browser.newContext({viewport:{width:1365,height:900}});await specContext.addInitScript(()=>{try{navigator.serviceWorker.register=async()=>undefined;}catch{}localStorage.setItem('liber.spec.v1',JSON.stringify({projects:{audit:{id:'audit',name:'Audit book'}},sections:{audit:{doors:{id:'doors',scheduleName:'Doors',kind:'spec',number:'081113',order:1,parts:{general:'General note'}}}},items:{audit:{one:{id:'one',sectionId:'doors',label:'Door 1',status:'active',spec:{notes:'Initial'}}}}}));localStorage.setItem('liber.spec.last','audit');});
 const spec=await specContext.newPage();spec.on('pageerror',e=>errors.push(e.message));await spec.goto(preview+'/liber-apps/apps/specifications/index.html');await spec.locator('[data-select-section="doors"]').click();await spec.locator('.sp-authored-spec summary').click();const expected=await spec.locator('.sp-authored-spec').evaluate(e=>e.open);
 for(let i=0;i<4;i++)await spec.evaluate(async n=>SpecStore.setDocIn('items','audit','one',{spec:{notes:'Updated '+n}}),i);
 assert.equal(await spec.locator('.sp-authored-spec').evaluate(e=>e.open),expected);await spec.locator('.sp-authored-spec summary').click();const opposite=!expected;await spec.evaluate(()=>SpecStore.setDocIn('items','audit','one',{spec:{notes:'Another update'}}));assert.equal(await spec.locator('.sp-authored-spec').evaluate(e=>e.open),opposite);await spec.screenshot({path:out+'/spec-disclosures.png'});pass('Open and closed Spec Book sections survive repeated realtime updates');
})().catch(async e=>{checks.push({name:'Audit browser journey',status:'FAIL',error:e.message,stack:e.stack});console.error(e.message);await page?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(errors.length)process.exitCode=1;fs.writeFileSync(out+'/result.json',JSON.stringify({preview,checks,errors},null,2));fs.writeFileSync(out+'/exit-status.txt',String(process.exitCode||0));});
